steps:
  # Generate a kubeconfig file for the given GKE cluster.
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'CLOUDSDK_PROJECT=${_CLOUDSDK_PROJECT}'
      - 'KUBECONFIG=/kube/config'      
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "$${CLOUDSDK_CONTAINER_CLUSTER}" \
          --project "$${CLOUDSDK_PROJECT}" \
          --zone "$${CLOUDSDK_COMPUTE_ZONE}"
    volumes:
      - name: 'kube'
        path: /kube

  # Update the Kubernetes deployment config.
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        kubectl apply --recursive -f kubernetes 
    volumes:
      - name: 'kube'
        path: /kube
