kind: Service
apiVersion: v1
metadata:
  name: node-helloworld
  namespace: default
spec:
  selector:
    app: node-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
